### ISSUE TITLE
Test-Class-Moose-0.68 no longer exports Test::Most functions into subclasses

### ISSUE THREAD

**Issue by mephinet** [test-class-moose/test-class-moose#62] opened 2016-04-27 16:26 UTC
The gist https://gist.github.com/mephinet/e15b01d6241f40f0f34c9cbaae35ea1d reproduces an issue we face since updating T:C:M to 0.68:
We have a class 'P', which uses T:C:M, and a subclass 'C' that extends 'P'. Within P, we use `ok`. In 0.67, this worked fine. In 0.68, we get:
>         #   Failed test 'test_something failed: Undefined subroutine &Test_Child::ok called at tcm2.pl line 12.
Reverting to 0.67 fixes the issue. This *could* be related to 05e0373e08ea35d0bdf9c48d0b7fe78c6e1f3244.

**Comment by autarch** [comment] 2016-04-27 16:38
I can't reproduce this with TCM 0.68 and the latest namespace::autoclean. Can you try upgrading to the latest ns::ac and seeing if that makes a difference?

**Comment by mephinet** [comment] 2016-04-27 16:56
I have the lastest namespace::autoclean as well, 0.28. Some further details:
* perl 5.20.2
* RHEL 6.5

> Versions for all modules listed in MYMETA.json (including optional ones):
> 
> === Configure Requires ===
> 
>     Module              Want Have
>     ------------------- ---- ----
>     ExtUtils::MakeMaker  any 7.04
> 
> === Build Requires ===
> 
>     Module              Want Have
>     ------------------- ---- ----
>     ExtUtils::MakeMaker  any 7.04
> 
> === Test Requires ===
> 
>     Module              Want     Have
>     ------------------- ---- --------
>     Carp::Always         any     0.13
>     ExtUtils::MakeMaker  any     7.04
>     File::Spec           any  3.48_01
>     Scalar::Util         any     1.45
>     Test::More          0.96 1.001014
>     Test::Requires       any     0.07
>     Test::Warnings       any    0.026
>     lib                  any     0.63
> 
> === Test Recommends ===
> 
>     Module           Want     Have
>     ------------ -------- --------
>     CPAN::Meta   2.120900 2.150005
>     Test::Output   0.0005     1.03
> 
> === Runtime Requires ===
> 
>     Module                         Want     Have
>     ---------------------------- ------ --------
>     Benchmark                       any     1.18
>     Carp                            any   1.3301
>     Class::MOP                      any   2.1605
>     File::Find                      any     1.27
>     File::Spec                      any  3.48_01
>     Import::Into                    any 1.002001
>     List::SomeUtils                 any     0.51
>     List::Util                      any     1.45
>     Moose                        2.0000   2.1605
>     Moose::Role                  2.0000   2.1605
>     Moose::Util::TypeConstraints    any   2.1605
>     Package::DeprecationManager    0.16     0.16
>     Parallel::ForkManager           any     1.11
>     Sub::Attribute                  any     0.05
>     TAP::Formatter::Color           any     3.30
>     TAP::Stream                    0.44     0.44
>     Test::Builder                   any 1.001014
>     Test::Most                     0.32     0.34
>     Try::Tiny                       any     0.20
>     namespace::autoclean            any     0.28
>     strict                          any     1.08
>     warnings                        any     1.23
> 
> === Runtime Recommends ===
> 
>     Module                  Want Have
>     --------------------- ------ ----
>     Parallel::ForkManager v0.7.6 1.11


and, now that I use cpanm to install 0.68 instead of carton, I see that one of the unittests is failing (this might be unrelated, though) :

> t/00-report-prereqs.t ...... ok
> syntax error at t/autouse.t line 17, near "ok my "
> Global symbol "$person" requires explicit package name at t/autouse.t line 17.
> Global symbol "$person" requires explicit package name at t/autouse.t line 22.
> Global symbol "$person" requires explicit package name at t/autouse.t line 24.
> Execution of t/autouse.t aborted due to compilation errors.
> t/autouse.t ................ 
> Dubious, test returned 255 (wstat 65280, 0xff00)
> No subtests run 
>

**Comment by autarch** [comment] 2016-04-27 18:05
I'm not seeing that test failure either.

    autarch@houseabsolute:~/projects/test-class-moose (master %=)$ cpanm --test-only Test::Class::Moose
    --> Working on Test::Class::Moose
    Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Test-Class-Moose-0.68.tar.gz ... OK
    Configuring Test-Class-Moose-0.68 ... OK
    Building and testing Test-Class-Moose-0.68 ... OK
    Successfully tested Test-Class-Moose-0.68

From the cpanm build.log

    cpanm (App::cpanminus) 1.7039 on perl 5.022001 built for x86_64-linux
    Work directory is /home/autarch/.cpanm/work/1461780248.15744
    You have make /usr/bin/make
    You have LWP 6.15
    You have /bin/tar: tar (GNU tar) 1.27.1
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.

    Written by John Gilmore and Jay Fenlason.
    You have /usr/bin/unzip
    Searching Test::Class::Moose () on cpanmetadb ...
    --> Working on Test::Class::Moose
    Fetching http://www.cpan.org/authors/id/D/DR/DROLSKY/Test-Class-Moose-0.68.tar.gz
    -> OK
    Unpacking Test-Class-Moose-0.68.tar.gz
    Entering Test-Class-Moose-0.68
    Checking configure dependencies from META.json
    Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.14)
    Configuring Test-Class-Moose-0.68
    Running Makefile.PL
    Checking if your kit is complete...
    Looks good
    Generating a Unix-style Makefile
    Writing Makefile for Test::Class::Moose
    Writing MYMETA.yml and MYMETA.json
    -> OK
    Checking dependencies from MYMETA.json ...
    Checking if you have Carp::Always 0 ... Yes (0.13)
    Checking if you have namespace::autoclean 0 ... Yes (0.28)
    Checking if you have warnings 0 ... Yes (1.34)
    Checking if you have strict 0 ... Yes (1.09)
    Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.14)
    Checking if you have List::Util 0 ... Yes (1.45)
    Checking if you have Parallel::ForkManager 0 ... Yes (1.18)
    Checking if you have lib 0 ... Yes (0.63)
    Checking if you have List::SomeUtils 0 ... Yes (0.51)
    Checking if you have Test::Builder 0 ... Yes (1.302013_014)
    Checking if you have Test::More 0.96 ... Yes (1.302013_014)
    Checking if you have Moose::Util::TypeConstraints 0 ... Yes (2.1605)
    Checking if you have Test::Warnings 0 ... Yes (0.026)
    Checking if you have Carp 0 ... Yes (1.38)
    Checking if you have TAP::Stream 0.44 ... Yes (0.44)
    Checking if you have Moose::Role 2.0000 ... Yes (2.1605)
    Checking if you have Class::MOP 0 ... Yes (2.1605)
    Checking if you have Package::DeprecationManager 0.16 ... Yes (0.16)
    Checking if you have File::Find 0 ... Yes (1.29)
    Checking if you have Moose 2.0000 ... Yes (2.1605)
    Checking if you have Try::Tiny 0 ... Yes (0.24)
    Checking if you have File::Spec 0 ... Yes (3.62)
    Checking if you have Sub::Attribute 0 ... Yes (0.05)
    Checking if you have TAP::Formatter::Color 0 ... Yes (3.36)
    Checking if you have Test::Requires 0 ... Yes (0.10)
    Checking if you have Scalar::Util 0 ... Yes (1.45)
    Checking if you have Import::Into 0 ... Yes (1.002005)
    Checking if you have Benchmark 0 ... Yes (1.2)
    Checking if you have Test::Most 0.32 ... Yes (0.34)
    Building and testing Test-Class-Moose-0.68
    cp lib/Test/Class/Moose/AttributeRegistry.pm blib/lib/Test/Class/Moose/AttributeRegistry.pm
    cp lib/Test/Class/Moose/Executor/Sequential.pm blib/lib/Test/Class/Moose/Executor/Sequential.pm
    cp lib/Test/Class/Moose/Tutorial.pm blib/lib/Test/Class/Moose/Tutorial.pm
    cp lib/Test/Class/Moose/Role/HasTimeReport.pm blib/lib/Test/Class/Moose/Role/HasTimeReport.pm
    cp lib/Test/Class/Moose/Executor/Parallel.pm blib/lib/Test/Class/Moose/Executor/Parallel.pm
    cp lib/Test/Class/Moose/Role/Executor.pm blib/lib/Test/Class/Moose/Role/Executor.pm
    cp lib/Test/Class/Moose/Role/ParameterizedInstances.pm blib/lib/Test/Class/Moose/Role/ParameterizedInstances.pm
    cp lib/Test/Class/Moose/Report.pm blib/lib/Test/Class/Moose/Report.pm
    cp lib/Test/Class/Moose.pm blib/lib/Test/Class/Moose.pm
    cp lib/Test/Class/Moose/Report/Instance.pm blib/lib/Test/Class/Moose/Report/Instance.pm
    cp lib/Test/Class/Moose/Load.pm blib/lib/Test/Class/Moose/Load.pm
    cp lib/Test/Class/Moose/Report/Class.pm blib/lib/Test/Class/Moose/Report/Class.pm
    cp lib/Test/Class/Moose/Role/Reporting.pm blib/lib/Test/Class/Moose/Role/Reporting.pm
    cp lib/Test/Class/Moose/Runner.pm blib/lib/Test/Class/Moose/Runner.pm
    cp lib/Test/Class/Moose/Role.pm blib/lib/Test/Class/Moose/Role.pm
    cp lib/Test/Class/Moose/Deprecated.pm blib/lib/Test/Class/Moose/Deprecated.pm
    cp lib/Test/Class/Moose/Report/Method.pm blib/lib/Test/Class/Moose/Report/Method.pm
    cp lib/Test/Class/Moose/Report/Time.pm blib/lib/Test/Class/Moose/Report/Time.pm
    cp lib/Test/Class/Moose/Config.pm blib/lib/Test/Class/Moose/Config.pm
    cp lib/Test/Class/Moose/Role/AutoUse.pm blib/lib/Test/Class/Moose/Role/AutoUse.pm
    cp lib/Test/Class/Moose/Role/Parallel.pm blib/lib/Test/Class/Moose/Role/Parallel.pm
    Manifying 21 pod documents
    PERL_DL_NONLAZY=1 "/home/autarch/perl5/perlbrew/perls/perl-5.22.1/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
    # 
    # Versions for all modules listed in MYMETA.json (including optional ones):
    # 
    # === Configure Requires ===
    # 
    #     Module              Want Have
    #     ------------------- ---- ----
    #     ExtUtils::MakeMaker  any 7.14
    # 
    # === Build Requires ===
    # 
    #     Module              Want Have
    #     ------------------- ---- ----
    #     ExtUtils::MakeMaker  any 7.14
    # 
    # === Test Requires ===
    # 
    #     Module              Want         Have
    #     ------------------- ---- ------------
    #     Carp::Always         any         0.13
    #     ExtUtils::MakeMaker  any         7.14
    #     File::Spec           any         3.62
    #     Scalar::Util         any         1.45
    #     Test::More          0.96 1.302013_014
    #     Test::Requires       any         0.10
    #     Test::Warnings       any        0.026
    #     lib                  any         0.63
    # 
    # === Test Recommends ===
    # 
    #     Module           Want     Have
    #     ------------ -------- --------
    #     CPAN::Meta   2.120900 2.150005
    #     Test::Output   0.0005     1.03
    # 
    # === Runtime Requires ===
    # 
    #     Module                         Want         Have
    #     ---------------------------- ------ ------------
    #     Benchmark                       any          1.2
    #     Carp                            any         1.38
    #     Class::MOP                      any       2.1605
    #     File::Find                      any         1.29
    #     File::Spec                      any         3.62
    #     Import::Into                    any     1.002005
    #     List::SomeUtils                 any         0.51
    #     List::Util                      any         1.45
    #     Moose                        2.0000       2.1605
    #     Moose::Role                  2.0000       2.1605
    #     Moose::Util::TypeConstraints    any       2.1605
    #     Package::DeprecationManager    0.16         0.16
    #     Parallel::ForkManager           any         1.18
    #     Sub::Attribute                  any         0.05
    #     TAP::Formatter::Color           any         3.36
    #     TAP::Stream                    0.44         0.44
    #     Test::Builder                   any 1.302013_014
    #     Test::Most                     0.32         0.34
    #     Try::Tiny                       any         0.24
    #     namespace::autoclean            any         0.28
    #     strict                          any         1.09
    #     warnings                        any         1.34
    # 
    # === Runtime Recommends ===
    # 
    #     Module                  Want Have
    #     --------------------- ------ ----
    #     Parallel::ForkManager v0.7.6 1.18
    # 
    t/00-report-prereqs.t ...... ok
    t/autouse.t ................ ok
    t/bare.t ................... ok



    t/basic.t .................. ok
    t/environment.t ............ ok
    t/include_classes.t ........ ok
    t/include_exclude.t ........ ok
    t/load.t ................... ok
    t/non-randomize-classes.t .. ok
    t/parallel-role.t .......... ok
    [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m
    t/parallel.t ............... ok
    t/parameterized.t .......... ok



    t/plans.t .................. ok
    t/reporting.t .............. ok

                #   Failed test at t/reportpassedlib/TestsFor/Fail.pm line 9.
                # Looks like you failed 1 test of 1.

            #   Failed test 'test_a_bad'
            #   at /home/autarch/.cpanm/work/1461780248.15744/Test-Class-Moose-0.68/blib/lib/Test/Class/Moose/Role/Executor.pm line 103.

                #   Failed test at t/reportpassedlib/TestsFor/Fail.pm line 17.
                # Looks like you failed 1 test of 1.

            #   Failed test 'test_b_bad'
            #   at /home/autarch/.cpanm/work/1461780248.15744/Test-Class-Moose-0.68/blib/lib/Test/Class/Moose/Role/Executor.pm line 103.
            # Looks like you failed 2 tests of 4.

    t/reportpassed.t ........... ok
    t/skip.t ................... ok
    t/skip_all.t ............... skipped: This test must always skip_all and must never fail
    t/tags.t ................... ok













    t/test_control_methods.t ... ok
    All tests successful.
    Files=19, Tests=131, 15 wallclock secs ( 0.12 usr  0.02 sys +  6.05 cusr  0.37 csys =  6.56 CPU)
    Result: PASS
    -> OK
    Successfully tested Test-Class-Moose-0.68

**Comment by mephinet** [comment] 2016-04-28 09:30
I think it's related to the version of Import::Into: when I upgrade to 1.2.3, the issue is gone. When I downgrade to 1.2.1, the unittest breaks again. Can you please check if you can reproduce this - and if so, bump the minimum version?

**Comment by autarch** [comment] 2016-04-28 14:41
Fixed in b302facc00f0073e26a73a9c4702dfd854428c1e. A new release will be out shortly.

**Closed by autarch** 2016-04-28 14:41 UTC

**Comment by mephinet** [comment] 2016-04-29 14:44
great, thanks!
